//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HorecaMebel.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HorecaMebel.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Über uns.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ich akzeptiere die AGB&apos;s &amp; Wiederrufsbelehrung *.
        /// </summary>
        public static string AcceptTernsAndConditions {
            get {
                return ResourceManager.GetString("AcceptTernsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACQUIRED.
        /// </summary>
        public static string ACQUIRED {
            get {
                return ResourceManager.GetString("ACQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In den Warenkorb.
        /// </summary>
        public static string AddInBasket {
            get {
                return ResourceManager.GetString("AddInBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anschrift.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sind Sie sicher, dass sie die Seite verlassen wollen?.
        /// </summary>
        public static string AreYouSureYouWantToDeleteThisElementFromBasket {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToDeleteThisElementFromBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessel.
        /// </summary>
        public static string Armchairs {
            get {
                return ResourceManager.GetString("Armchairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niedrigster Preis.
        /// </summary>
        public static string AscendingOrder {
            get {
                return ResourceManager.GetString("AscendingOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Österreich.
        /// </summary>
        public static string Austria {
            get {
                return ResourceManager.GetString("Austria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurück.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rücken.
        /// </summary>
        public static string BackOptions {
            get {
                return ResourceManager.GetString("BackOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belgien.
        /// </summary>
        public static string Belguim {
            get {
                return ResourceManager.GetString("Belguim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BY DESIGN.
        /// </summary>
        public static string BYDESIGN {
            get {
                return ResourceManager.GetString("BYDESIGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stühle.
        /// </summary>
        public static string Chairs {
            get {
                return ResourceManager.GetString("Chairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ort.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farbe.
        /// </summary>
        public static string Colour {
            get {
                return ResourceManager.GetString("Colour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----------------------------------.
        /// </summary>
        public static string ComboBoxDelimiter {
            get {
                return ResourceManager.GetString("ComboBoxDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impressum.
        /// </summary>
        public static string CompanyInformation {
            get {
                return ResourceManager.GetString("CompanyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontaktformular.
        /// </summary>
        public static string ContactForm {
            get {
                return ResourceManager.GetString("ContactForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihre Nachricht wurde erfolgreich gesendet.
        /// </summary>
        public static string ContactFormSubmitted {
            get {
                return ResourceManager.GetString("ContactFormSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menge.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sitzwürfel.
        /// </summary>
        public static string CubeSeats {
            get {
                return ResourceManager.GetString("CubeSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MwSt. (19%):.
        /// </summary>
        public static string DDSInBasket {
            get {
                return ResourceManager.GetString("DDSInBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lieferung.
        /// </summary>
        public static string Delivery {
            get {
                return ResourceManager.GetString("Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesamttiefe.
        /// </summary>
        public static string Depth {
            get {
                return ResourceManager.GetString("Depth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Höchster Preis.
        /// </summary>
        public static string DescendingOrder {
            get {
                return ResourceManager.GetString("DescendingOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produktinformationen.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element  wurde in den Warenkorb gelegt..
        /// </summary>
        public static string ElementAddedInTheBasket {
            get {
                return ResourceManager.GetString("ElementAddedInTheBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server side error..
        /// </summary>
        public static string ElementErrorInController {
            get {
                return ResourceManager.GetString("ElementErrorInController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string EMail {
            get {
                return ResourceManager.GetString("EMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AGB.
        /// </summary>
        public static string Faqs {
            get {
                return ResourceManager.GetString("Faqs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dies ist ein Pflichtfeld..
        /// </summary>
        public static string FieldIsRequired {
            get {
                return ResourceManager.GetString("FieldIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorname.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestell.
        /// </summary>
        public static string FrameOptions {
            get {
                return ResourceManager.GetString("FrameOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kommentar.
        /// </summary>
        public static string FreeText {
            get {
                return ResourceManager.GetString("FreeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesamtsumme:.
        /// </summary>
        public static string FullPriceInBasket {
            get {
                return ResourceManager.GetString("FullPriceInBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zwischensumme:.
        /// </summary>
        public static string FurniturePriceInBasket {
            get {
                return ResourceManager.GetString("FurniturePriceInBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deutschland.
        /// </summary>
        public static string Germany {
            get {
                return ResourceManager.GetString("Germany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesamthöhe.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niederlande.
        /// </summary>
        public static string Holand {
            get {
                return ResourceManager.GetString("Holand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startseite.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to horecamoebel.de.
        /// </summary>
        public static string HorecaLogo {
            get {
                return ResourceManager.GetString("HorecaLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ich akzeptiere die AGB&apos;s &amp; Wiederrufsbelehrung.
        /// </summary>
        public static string IAgreeWithTermsAndConditions {
            get {
                return ResourceManager.GetString("IAgreeWithTermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to horecamoebel.de.
        /// </summary>
        public static string Interior {
            get {
                return ResourceManager.GetString("Interior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nachname.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Füße.
        /// </summary>
        public static string LegOptions {
            get {
                return ResourceManager.GetString("LegOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nachricht.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MORE STYLE.
        /// </summary>
        public static string MORESTYLE {
            get {
                return ResourceManager.GetString("MORESTYLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herr.
        /// </summary>
        public static string Mr {
            get {
                return ResourceManager.GetString("Mr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frau.
        /// </summary>
        public static string Mrs {
            get {
                return ResourceManager.GetString("Mrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mein Warenkorb.
        /// </summary>
        public static string MyBag {
            get {
                return ResourceManager.GetString("MyBag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuer Preis.
        /// </summary>
        public static string NewPrice {
            get {
                return ResourceManager.GetString("NewPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a valid email address..
        /// </summary>
        public static string NoTValidEmailAddress {
            get {
                return ResourceManager.GetString("NoTValidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auftrag.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestellvorgang.
        /// </summary>
        public static string OrderProcess {
            get {
                return ResourceManager.GetString("OrderProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahlungsarten.
        /// </summary>
        public static string PaymentProcess {
            get {
                return ResourceManager.GetString("PaymentProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datenschutz.
        /// </summary>
        public static string PersonalDetails {
            get {
                return ResourceManager.GetString("PersonalDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihre E-Mail-Adresse.
        /// </summary>
        public static string PleaseProvideValidEmail {
            get {
                return ResourceManager.GetString("PleaseProvideValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte wählen.
        /// </summary>
        public static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postleitzahl.
        /// </summary>
        public static string PostCode {
            get {
                return ResourceManager.GetString("PostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summe.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preise zzgl. gesetzlicher MwSt. zzgl. Versandkosten.
        /// </summary>
        public static string PriceDescriptionText {
            get {
                return ResourceManager.GetString("PriceDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AGB.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artikel.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte füllen Sie alle erforderlichen Felder aus.
        /// </summary>
        public static string ProvideCorrectValue {
            get {
                return ResourceManager.GetString("ProvideCorrectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referenzen.
        /// </summary>
        public static string References {
            get {
                return ResourceManager.GetString("References", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suche.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sitz.
        /// </summary>
        public static string SeatOptions {
            get {
                return ResourceManager.GetString("SeatOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senden.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impressum.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Êinzelpreis.
        /// </summary>
        public static string SinglePrice {
            get {
                return ResourceManager.GetString("SinglePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farbe.
        /// </summary>
        public static string SkinOptions {
            get {
                return ResourceManager.GetString("SkinOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sofas.
        /// </summary>
        public static string Sofas {
            get {
                return ResourceManager.GetString("Sofas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widerrufsbelehrung.
        /// </summary>
        public static string StockReturn {
            get {
                return ResourceManager.GetString("StockReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summe.
        /// </summary>
        public static string Sum {
            get {
                return ResourceManager.GetString("Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schweiz.
        /// </summary>
        public static string Swizz {
            get {
                return ResourceManager.GetString("Swizz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AGB.
        /// </summary>
        public static string TearmsAndConditions {
            get {
                return ResourceManager.GetString("TearmsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string Telefon {
            get {
                return ResourceManager.GetString("Telefon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lieferzeit 4 - 6 Wochen.
        /// </summary>
        public static string TimeForProduction {
            get {
                return ResourceManager.GetString("TimeForProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versandkosten:.
        /// </summary>
        public static string TransportPriceInBasket {
            get {
                return ResourceManager.GetString("TransportPriceInBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USt-ID-Nummer.
        /// </summary>
        public static string VATNumber {
            get {
                return ResourceManager.GetString("VATNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wir werden uns umgehend mit Ihnen in Verbindung setzen.
        /// </summary>
        public static string WeWillBeInTouchSoon {
            get {
                return ResourceManager.GetString("WeWillBeInTouchSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesamtbreite.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beizton.
        /// </summary>
        public static string WoodColor {
            get {
                return ResourceManager.GetString("WoodColor", resourceCulture);
            }
        }
    }
}
