//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HorecaMebel.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int id { get; set; }
        public string order_Guid { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string PostCode { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string Company { get; set; }
        public string VAT { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Comment { get; set; }
        public Nullable<double> FurniturePrice { get; set; }
        public Nullable<double> TransportPrice { get; set; }
        public Nullable<double> DDSPrice { get; set; }
        public Nullable<double> FullPrice { get; set; }
        public Nullable<System.DateTime> OrderDateTime { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
