//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HorecaMebel.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SofaAdditionalPhoto
    {
        public int id { get; set; }
        public int SofaId { get; set; }
        public string ImagePath { get; set; }
    }
}
