//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HorecaMebel.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SofasInOrder
    {
        public int id { get; set; }
        public int orderId { get; set; }
        public int sofaId { get; set; }
        public int count { get; set; }
        public string skin { get; set; }
        public double price { get; set; }
    }
}
